development:
  adapter: mysql2
  encoding: utf8
  database: movie_hall_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  database: movie_hall_test
  pool: 5
  username: root